set background=dark
set ai si wrap
set mouse=n
set noswapfile
set hlsearch
set nocompatible
set encoding=utf-8
set number relativenumber
set splitbelow splitright
set expandtab softtabstop=4 shiftwidth=4
set nowrapscan
set tw=90

"filetype plugin on
"filetype indent on
syntax on

map <C-j> <C-W>j
map <C-h> <C-W>h
map <C-k> <C-W>k
map <C-l> <C-W>l

